-- ============================================
-- InsightCart E-commerce Analytics
-- SQL Analysis Views
-- ============================================


-- 1. Revenue by Customer State
-- Calculates total revenue generated from each customer state.

SELECT
    c.customer_state AS customer_state,
    ROUND(SUM(p.payment_value), 2) AS Revenue
FROM
    insightcart.customers c
JOIN
    insightcart.orders o
    ON c.customer_id = o.customer_id
JOIN
    insightcart.payments p
    ON o.order_id = p.order_id
GROUP BY
    c.customer_state;


-- 2. Monthly Revenue
-- Calculates total revenue for each month.

SELECT
    DATE_FORMAT(o.order_purchase_timestamp, '%Y-%M') AS Month,
    ROUND(SUM(p.payment_value), 2) AS Revenue
FROM
    insightcart.orders o
JOIN
    insightcart.payments p
    ON o.order_id = p.order_id
GROUP BY
    DATE_FORMAT(o.order_purchase_timestamp, '%Y-%M')
ORDER BY
    MIN(o.order_purchase_timestamp);


-- 3. Revenue by Seller
-- Calculates revenue generated by each seller,
-- including product price and freight value.

SELECT
    order_items.seller_id AS seller_id,
    ROUND(
        SUM(order_items.price + order_items.freight_value),
        2
    ) AS Revenue
FROM
    insightcart.order_items
GROUP BY
    order_items.seller_id;


-- 4. Revenue by Product Category
-- Calculates total product revenue for each category.

SELECT
    pr.product_category_name AS product_category_name,
    ROUND(SUM(oi.price), 2) AS Revenue
FROM
    insightcart.products pr
JOIN
    insightcart.order_items oi
    ON pr.product_id = oi.product_id
GROUP BY
    pr.product_category_name;